version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: windkube-upsnap_server_1
      APP_PORT: 8090
      PROXY_AUTH_ADD: "false"
    
  server:
    image: ghcr.io/ajnart/homarr:0.15.6
    restart: on-failure
    network_mode: host
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000

    volumes:
      - ${APP_DATA_DIR}/data:/app/pb_data

