version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: windkube-homarr_server_1
      APP_PORT: 7575
      PROXY_AUTH_ADD: "false"
    
  server:
    image: ghcr.io/ajnart/homarr:0.15.6
    restart: on-failure
    ports:
    - 7575
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_GID=995 # Must be same as host docker group id
      - DATABASE_URL=file:/app/data/configs/db.sqlite
    volumes:
      - "${APP_DATA_DIR}/configs:/app/data/configs"
      - "${APP_DATA_DIR}/icons:/app/public/icons"
      - "/var/run/docker.sock:/var/run/docker.sock"
