version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: windkube-zoraxy_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"

  server:
    image: zoraxydocker/zoraxy:3.0.3
    ports:
      - 80
      - 10443:443
      - 8000
    volumes:
      - ${APP_DATA_DIR}/data:/opt/zoraxy/config/