version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: windkube-zoraxy_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"

  server:
    image: zoraxydocker/zoraxy:v3.1.6
    ports:
      - 10080:80
      - 10443:443
      - 8000
    volumes:
      - ${APP_DATA_DIR}/data:/opt/zoraxy/config/
      - "/var/run/docker.sock:/var/run/docker.sock"