services:
  server:
    image: henrygd/beszel:0.9.1
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8094:8090
    volumes:
      - "${APP_DATA_DIR}/data/beszel_data"